[package]
name = "zisch"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
camino.workspace = true
blake3.workspace = true

diesel.workspace = true
libsqlite3-sys.workspace = true