[package]
name = "model"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
