[workspace]
resolver = "2"
members = ["cli", "loader", "rules", "store"]

[workspace.dependencies]
starlark = { version = "0.13.0", features = [] }

include_dir = "0.7.4"

# data types
url = { version = "2.5.4", features = ["serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
uuid = { version = "1.13.2", features = ["serde"] }
camino = { version = "1.1.9", features = ["serde1", "proptest1"] }

# serialization
serde = "1.0.218"
serde_json = "1.0.139"

# data structures
ahash = "0.8.11"

# error handling
thiserror = "2.0.11"
anyhow = "1.0.96"

# utility
dupe = "0.9.1"
quote = "1.0.38"
tempfile = "3.17.1"

# cli
bpaf = "0.9.16"

# dev
prop-test = "0.1.1"
