[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true}
thiserror = { workspace = true }
tempfile = {  workspace = true }
camino = { workspace = true }
