[package]
name = "zopf"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
camino.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
anyhow.workspace = true