[package]
name = "zwischen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true

blake3.workspace = true
camino.workspace = true
serde.workspace = true

tempfile.workspace = true
nix.workspace = true
