[package]
name = "loader"
version = "0.1.0"
edition = "2024"

[dependencies]
starlark = { workspace = true }

thiserror = { workspace = true }
anyhow = { workspace = true }
dupe = { workspace = true }
camino = { workspace = true }
tracing = { workspace = true }

store = { path = "../store" }
