[package]
name = "rules"
version = "0.1.0"
edition = "2024"

[dependencies]
include_dir = {  workspace = true }
camino = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }

store = { path = "../directories" }
