name: rust build

on: [push, pull_request, merge_group]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest

    name: Test `cargo check/test/build` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v5

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.1

      - run: |
          cargo check
          cargo check --tests
          cargo build --package zaun
          cargo test
          cargo clippy
          cargo clippy --tests
